### PR TITLE
CSS Issue Fix

### PR DESCRIPTION
**Pull request by LeeGDavis**
* Corrected misspelling of `font-style`

ping @taylor-work

### CODE REVIEW

**Comment by dubharmonic** [comment]
https://media.giphy.com/media/Yanv5CQha50Uo/giphy.gif @LeeGDavis !

**Comment by taylor-work** [comment]
:+1:

**Comment by thegoldentoilet** [comment]
unsubscribe.

**Comment by dubharmonic** [comment]
@thegoldentoilet please advise

**Pull request merged**
